#! /usr/bin/python3

from os import listdir
from os.path import isfile, join
import datetime

today = str(datetime.datetime.now().date())

# getting all file names
mypath = "/home/khashayar/Documents/notes/"
dates = [f for f in listdir(mypath) if isfile(join(mypath, f))]

if (today not in dates):
	new_note = open('/home/khashayar/Documents/notes/' + today,"w")
	new_note.write(today + "\n..........\n")
	new_note.close()
